config/routes.rb
Rails.application.routes.draw do
  resources :dtp_minutes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dtp_minute.rb
class DtpMinute < ApplicationRecord
    before_create :retrieve_value 
    
    def retrieve_value
        require 'uri'
        require 'net/http'

        uri = URI("https://itsmybike-staging.cloud/api/monitoring/datapoints_last_minute")
        req = Net::HTTP::Get.new(uri)
        req['Authorization'] = "Token token=8fe569ac"
        req['Content-Type'] = "application/json"
        res = Net::HTTP.start(uri.hostname, uri.port, use_ssl: uri.scheme == 'https') do |http|
            http.request(req)
        end
        self.amount = res.body.to_i
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dtp_minutes_controller.rb
class DtpMinutesController < ApplicationController
  before_action :set_dtp_minute, only: %i[ show edit update destroy ]

  # GET /dtp_minutes or /dtp_minutes.json
  def index
    @dtp_minutes = DtpMinute.all
  end

  # GET /dtp_minutes/1 or /dtp_minutes/1.json
  def show
  end

  # GET /dtp_minutes/new
  def new
    @dtp_minute = DtpMinute.new
  end

  # GET /dtp_minutes/1/edit
  def edit
  end

  # POST /dtp_minutes or /dtp_minutes.json
  def create
    @dtp_minute = DtpMinute.new(dtp_minute_params)

    respond_to do |format|
      if @dtp_minute.save
        format.html { redirect_to dtp_minute_url(@dtp_minute), notice: "Dtp minute was successfully created." }
        format.json { render :show, status: :created, location: @dtp_minute }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dtp_minute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dtp_minutes/1 or /dtp_minutes/1.json
  def update
    respond_to do |format|
      if @dtp_minute.update(dtp_minute_params)
        format.html { redirect_to dtp_minute_url(@dtp_minute), notice: "Dtp minute was successfully updated." }
        format.json { render :show, status: :ok, location: @dtp_minute }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dtp_minute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dtp_minutes/1 or /dtp_minutes/1.json
  def destroy
    @dtp_minute.destroy

    respond_to do |format|
      format.html { redirect_to dtp_minutes_url, notice: "Dtp minute was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dtp_minute
      @dtp_minute = DtpMinute.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dtp_minute_params
      params.fetch(:dtp_minute, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dtp_minutes_helper.rb
module DtpMinutesHelper
end

app/views/dtp_minutes/_dtp_minute.html.erb
<div id="<%= dom_id dtp_minute %>">
</div>

app/views/dtp_minutes/_form.html.erb
<%= form_with(model: dtp_minute) do |form| %>
  <% if dtp_minute.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dtp_minute.errors.count, "error") %> prohibited this dtp_minute from being saved:</h2>

      <ul>
        <% dtp_minute.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dtp_minutes/edit.html.erb
<h1>Editing dtp minute</h1>

<%= render "form", dtp_minute: @dtp_minute %>

<br>

<div>
  <%= link_to "Show this dtp minute", @dtp_minute %> |
  <%= link_to "Back to dtp minutes", dtp_minutes_path %>
</div>

app/views/dtp_minutes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dtp minutes</h1>

<div id="dtp_minutes">
  <% @dtp_minutes.each do |dtp_minute| %>
    <%= render dtp_minute %>
    <p>
      <%= link_to "Show this dtp minute", dtp_minute %>
    </p>
  <% end %>
</div>

<%= link_to "New dtp minute", new_dtp_minute_path %>

app/views/dtp_minutes/new.html.erb
<h1>New dtp minute</h1>

<%= render "form", dtp_minute: @dtp_minute %>

<br>

<div>
  <%= link_to "Back to dtp minutes", dtp_minutes_path %>
</div>

app/views/dtp_minutes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dtp_minute %>

<div>
  <%= link_to "Edit this dtp minute", edit_dtp_minute_path(@dtp_minute) %> |
  <%= link_to "Back to dtp minutes", dtp_minutes_path %>

  <%= button_to "Destroy this dtp minute", @dtp_minute, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Datapoint</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>